### ISSUE TITLE
ELECTRON_OZONE_PLATFORM_HINT Breaks Cider 2.x

### ISSUE THREAD

**Issue by ellwoodb** [leonmslz/dots#1]
ELECTRON_OZONE_PLATFORM_HINT = "auto" seems to break the new version of Cider. Fix pls :D

**Comment by leonmslz** [comment]
Removed ELECTRON_OZONE_PLATFORM_HINT from nvidia.nix :D

**Comment by ellwoodb** [comment]
Nice.

**Comment by ellwoodb** [comment]
very well done
